apiVersion: v1
kind: Service
metadata:
  name: {{ template "dvss-helm.fullname" . }}-scheduler
  labels:
    app: {{ template "dvss-helm.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "dvss-helm.chart" . }}
    component: scheduler
spec:
  ports:
    - name: {{ template "dvss-helm.fullname" . }}-scheduler
      port: {{ .Values.scheduler.servicePort }}
      targetPort: 8786
      nodePort: {{ .Values.scheduler.nodePort }}
    - name: {{ template "dvss-helm.fullname" . }}-webui
      port: {{ .Values.webUI.servicePort }}
      targetPort: 8787
      nodePort: {{ .Values.webUI.nodePort }}
  selector:
    app: {{ template "dvss-helm.name" . }}
    release: {{ .Release.Name | quote }}
    component: scheduler
  type: {{ .Values.scheduler.serviceType }}
